// SMPLModel.h
// ----------
// Interface for the SMPL (Skinned Multi-Person Linear) parametric body model.
// Responsibilities:
//  - Load SMPL model data
//  - Reconstruct mesh from pose and shape parameters
// Used by:
//  - FittingOptimizer
//  - Visualization
// ----------

#pragma once

#include <vector>
#include <string>
#include <Eigen/Dense>

// A simple mesh container for SMPL output.
//
// NOTE: We use Eigen types here because later optimization code will
//       operate heavily on matrices/vectors. Visualization code can
//       convert these to OpenCV or other formats when needed.
struct SMPLMesh
{
    // size: numVertices, positions in world or model space
    std::vector<Eigen::Vector3f> vertices;
    
    // size: numFaces, triangle vertex indices
    std::vector<Eigen::Vector3i> faces;    

    // Saves the mesh to OBJ format
    bool save(const std::string& path) const;
};

class SMPLModel
{
public:
    SMPLModel() = default;

    // Load SMPL model parameters from a JSON file generated by preprocess.py.
    //
    // Expected keys in the JSON (see preprocess.py):
    //   - "vertices_template"  : (6890, 3)
    //   - "face_indices"       : (F, 3)
    //   - "shape_blend_shapes" : (6890, 3, 10)
    //   - "pose_blend_shapes"  : (6890, 3, 207)
    //   - "joint_regressor"    : (24, 6890)
    //   - "weights"            : (6890, 24)
    //   - "kinematic_tree"     : (2, 24)
    bool loadFromJson(const std::string& jsonPath);

    // Set SMPL pose parameters (e.g. 72 axis-angle parameters).
    void setPose(const std::vector<double>& poseParams);

    // Set SMPL shape parameters (e.g. 10 betas).
    void setShape(const std::vector<double>& shapeParams);

    // Get the current mesh based on pose and shape parameters.
    SMPLMesh getMesh() const;

    // Get posed 3D joint positions (one row per joint, columns = x,y,z).
    // Updated to return MatrixXd for precision compatibility with optimization.
    Eigen::MatrixXd getJointPositions() const;

    // These return const references to the SMPL model data,
    // allowing external cost functors to access them efficiently for optimization.
    const Eigen::MatrixXd& getTemplateVertices() const { return templateVertices_; }
    const Eigen::MatrixXd& getShapeBlendShapes() const { return shapeBlendShapes_; }
    const Eigen::MatrixXd& getPoseBlendShapes() const  { return poseBlendShapes_; }
    const Eigen::MatrixXd& getJointRegressor() const   { return jointRegressor_; }
    const Eigen::MatrixXd& getWeights() const          { return weights_; }
    const Eigen::MatrixXi& getKinematicTree() const    { return kinematicTree_; }
    const Eigen::MatrixXi& getFaces() const            { return faces_; }

private:

    using MatrixXd = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>;
    using MatrixXi = Eigen::Matrix<int,   Eigen::Dynamic, Eigen::Dynamic>;

    // --------- Model data (loaded from JSON) ---------

    // (numVertices, 3)
    MatrixXd templateVertices_;

    // (numFaces, 3) triangle indices
    MatrixXi faces_;

    // Shape blendshapes, flattened as (numVertices * 3, numShapeCoeffs)
    MatrixXd shapeBlendShapes_;

    // Pose blendshapes, flattened as (numVertices * 3, numPoseCoeffs)
    MatrixXd poseBlendShapes_;

    // Joint regressor: (numJoints, numVertices)
    MatrixXd jointRegressor_;

    // Weights: (numVertices, numJoints)
    MatrixXd weights_;

    // Kinematic Tree: (2, numJoints)
    MatrixXi kinematicTree_;      

    // --------- SMPL parameters ---------
    Eigen::VectorXd poseParams_ = Eigen::VectorXd::Zero(72);  
    Eigen::VectorXd shapeParams_ = Eigen::VectorXd::Zero(10);

    // --- SMPL internal helpers ---

    // Rodrigues rotation: axis-angle (3,) → rotation matrix (3x3)
    Eigen::Matrix3d rodrigues(const Eigen::Vector3d& r) const;

    // Compute joint locations from vertices
    Eigen::MatrixXd computeJoints(const Eigen::MatrixXd& vertices) const;

    // Compute global joint transforms (4x4 matrices)
    std::vector<Eigen::Matrix4d> computeGlobalTransforms(
        const Eigen::MatrixXd& J,
        const std::vector<Eigen::Matrix3d>& rotations
    ) const;

};